import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import { PHProvider } from "./providers";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

const PostHogPageView = dynamic(() => import("./PostHogPageView"), {
  ssr: false,
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-full h-full">
      <PHProvider>
        <body className={`${inter.className} w-full h-full`}>
          <PostHogPageView />
          <main className="w-full h-full"> {children}</main>
          <Toaster />
        </body>
      </PHProvider>
    </html>
  );
}
